/**
 * Created by Administrator on 4/24/2017.
 */
export default {
  login: 'LOGIN',
  signUp: 'SIGN_UP',
  logout: 'LOGOUT',
  downloadWallet: 'DOWNLOAD_WALLET',
  bid: 'BID',
  ask: 'ASK',
  redeem: 'REDEEM',
  transfer: 'TRANSFER',
  cancel: 'CANCEL',
  setWallet: 'SET_WALLET',
  setUID: 'SET_UID',
  setDeliver: 'SET_DELIVER',
  setReceive: 'SET_RECEIVE',
  setAsset: 'SET_ASSET',
  getAsset: 'GET_ASSET',
  getUID: 'GET_UID',
  getMarkets: 'GET_MARKETS',
  getHistory: 'GET_HISTORY',
  getOrder: 'GET_ORDER',
  setWif: 'GET_WIF',
  setFileName: 'SET_FILE_NAME',
  getBlock: 'GET_BLOCK',
  setBlock: 'SET_BLOCK',
  getICO: 'GET_ICO',
  bidICO: 'BID_ICO',
  askICO: 'ASK_ICO',
  getIO: 'GET_ICO_ORDER',
  setWalletTemporary: 'SET_WALLET_TEMPORARY',
  getMarketsById: 'GET_MARKETSBYID',
  sendAsk: 'SEND_ASK',
  sendBid: 'SEND_BID',
  sendFreeAsk: 'SEND_FREE_ASK',
  sendFreeBid: 'SEND_FREE_BID',
  otcSign: 'OTC_SIGN',
  getPriceById: 'GET_PRICEBYID',
  getRedeem: 'GET_REDEEM',
  getOrderByAddress: 'GET_ORDER_BY_ADDRESS',
  getHistoryById: 'GET_HISTORY_BY_ID',
  getMyHistoryById: 'GET_MY_HISTORY_BY_ID'
}
